return {

-- ================= 5 ESTRELLAS =================
{ title = "Abara: Complete Deluxe Edition", category = "Manga/Manhua", rating = 5 },
{ title = "Rebelión en la granja", category = "book", rating = 5, badge = "📝", link = "https://alunya.cat/alan/_aforario.html#rebeli%C3%B3n-en-la-granja-george-orwell" },
{ title = "Bleach 1: The Death and the Strawberry", category = "book", rating = 5 },
{ title = "Claymore Complete Box Set: Volumes 1-27 with Premium", category = "Manga/Manhua", rating = 5 },
{ title = "Cometas en el cielo", category = "book", rating = 5 },
{ title = "Crime and Punishment", category = "book", rating = 5 },
{ title = "Cuentos completos de Roald Dahl", category = "book", rating = 5, badge = "📝", link = "https://alunya.cat/alan/_aforario.html#cuentos-roald-dahl" },
{ title = "Distant sky #1", category = "Manga/Manhua", rating = 5 },
{ title = "Du mouvement de la Terre, tome 1", category = "Manga/Manhua", rating = 5 },
{ title = "Eden: It's an Endless World, Volume 1 (Eden: It's an Endless World, #1)", category = "Manga/Manhua", rating = 5 },
{ title = "Eleceed", category = "Manga/Manhua", rating = 5 },
{ title = "Eureka Seven Gravity Boys & Lifting Girl, Vol. 2", category = "Manga/Manhua", rating = 5 },
{ title = "Fahrenheit 451", category = "book", rating = 5, badge = "📝", link = "https://alunya.cat/alan/_aforario.html#fahrenheit-451-ray-bradbury" },
{ title = "Fullmetal Alchemist, Vol. 1", category = "Manga/Manhua", rating = 5 },
{ title = "GTO: Great Teacher Onizuka, Vol. 1", category = "Manga/Manhua", rating = 5 },
{ title = "Gantz/1", category = "Manga/Manhua", rating = 5 },
{ title = "Horimiya, Vol. 1", category = "Manga/Manhua", rating = 5 },
{ title = "Kino's Journey: The Beautiful World", category = "Manga/Manhua", rating = 5 },
{ title = "La sombra del viento", category = "book", rating = 5, badge = "📝", link = "https://alunya.cat/alan/_aforario.html#la-sombra-del-viento-carlos-ruiz-zaf%C3%B3n" },
{ title = "La utilidad de lo inútil: Manifiesto", category = "book", rating = 5 },
{ title = "Marina", category = "book", rating = 5 },
{ title = "Naoki Urasawa's Monster, Volume 1: Herr Dr. Tenma", category = "Manga/Manhua", rating = 5 },
{ title = "Naruto, Vol. 1: Uzumaki Naruto", category = "Manga/Manhua", rating = 5 },
{ title = "ROUTE END 1", category = "Manga/Manhua", rating = 5 },
{ title = "ReLIFE 1", category = "Manga/Manhua", rating = 5 },
{ title = "Sanctuary", category = "Manga/Manhua", rating = 5 },
{ title = "Solanin", category = "Manga/Manhua", rating = 5 },
{ title = "Solo leveling - light Novel", category = "Manga/Manhua", rating = 5 },
{ title = "Sun-Ken Rock, Tome 1", category = "Manga/Manhua", rating = 5 },
{ title = "Sundome, Vol. 1", category = "Manga/Manhua", rating = 5 },
{ title = "The Beginning After the End, Vol. 1", category = "Manga/Manhua", rating = 5 },
{ title = "The Girl from the Other Side: Siúil, a Rún, Vol. 1", category = "Manga/Manhua", rating = 5 },
{ title = "The Hitchhiker's Guide to the Galaxy #1 (Graphic Novel)", category = "Manga/Manhua", rating = 5 },
{ title = "The Hunger Games", category = "book", rating = 5 },
{ title = "The Promised Neverland, Vol. 1: Grace Field House", category = "Manga/Manhua", rating = 5 },
{ title = "Tokyo Ghoul, Vol. 1", category = "Manga/Manhua", rating = 5 },
{ title = "Tokyo Ghoul: re, Vol. 2", category = "Manga/Manhua", rating = 5 },
{ title = "Tokyo Revengers, Vol. 1", category = "Manga/Manhua", rating = 5 },
{ title = "Un Mundo Feliz", category = "book", rating = 5 },
{ title = "Under the distant sky", category = "Manga/Manhua", rating = 5 },
{ title = "Vive como un mendigo, baila como un rey", category = "book", rating = 5 },
{ title = "Weak Hero, Season 1", category = "Manga/Manhua", rating = 5 },
{ title = "あつまれ! 学園天国 1", category = "Manga/Manhua", rating = 5 },
{ title = "おもいでエマノン", category = "Manga/Manhua", rating = 5 },
{ title = "ヒナまつり 1", category = "Manga/Manhua", rating = 5 },
{ title = "不能犯 1", category = "Manga/Manhua", rating = 5 },
{ title = "僕だけがいない街 1", category = "Manga/Manhua", rating = 5 },
{ title = "Alan Wake", category = "game", rating = 5 },
{ title = "Dark Souls: Prepare to Die Edition", category = "game", rating = 5 },
{ title = "Fallout: New Vegas", category = "game", rating = 5 },
{ title = "Pokémon Emerald Version", category = "game", rating = 5 },
{ title = "A Silent Voice: The Movie", category = "movie", rating = 5 },
{ title = "A Silent Voice: The Movie", category = "movie", rating = 5 },
{ title = "Apollo 11", category = "movie", rating = 5 },
{ title = "Arrival", category = "movie", rating = 5 },
{ title = "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan", category = "movie", rating = 5 },
{ title = "Cold Pursuit", category = "movie", rating = 5 },
{ title = "District 9", category = "movie", rating = 5 },
{ title = "Fight Club", category = "movie", rating = 5 },
{ title = "Gattaca", category = "movie", rating = 5 },
{ title = "Hacksaw Ridge", category = "movie", rating = 5 },
{ title = "Horrible Bosses", category = "movie", rating = 5 },
{ title = "Norbit", category = "movie", rating = 5 },
{ title = "Princesa", category = "movie", rating = 5 },
{ title = "Princesses", category = "movie", rating = 5 },
{ title = "Project X", category = "movie", rating = 5 },
{ title = "The Bourne Identity", category = "movie", rating = 5 },
{ title = "The Bourne Supremacy", category = "movie", rating = 5 },
{ title = "The Bourne Ultimatum", category = "movie", rating = 5 },
{ title = "The Hangover", category = "movie", rating = 5 },
{ title = "The Matrix", category = "movie", rating = 5 },
{ title = "The Matrix Reloaded", category = "movie", rating = 5 },
{ title = "The Matrix Revolutions", category = "movie", rating = 5 },
{ title = "The Truman Show", category = "movie", rating = 5 },
{ title = "We're the Millers", category = "movie", rating = 5 },
{ title = "Attack on Titan", category = "tv", rating = 5 },
{ title = "Baki the Grappler", category = "tv", rating = 5 },
{ title = "Banana Fish", category = "tv", rating = 5 },
{ title = "Berserk", category = "tv", rating = 5 },
{ title = "Chernobyl", category = "tv", rating = 5 },
{ title = "Classroom of the Elite", category = "tv", rating = 5 },
{ title = "Claymore", category = "tv", rating = 5 },
{ title = "Code Geass: Lelouch of the Rebellion", category = "tv", rating = 5 },
{ title = "Dbz Abridged", category = "tv", rating = 5 },
{ title = "Dragon Ball Z Kai", category = "tv", rating = 5 },
{ title = "ERASED", category = "tv", rating = 5 },
{ title = "Hunter x Hunter", category = "tv", rating = 5 },
{ title = "Hunter x Hunter", category = "tv", rating = 5 },
{ title = "Now and Then, Here and There", category = "tv", rating = 5 },
{ title = "Prison School", category = "tv", rating = 5 },
{ title = "Rainbow", category = "tv", rating = 5 },
{ title = "Steins;Gate", category = "tv", rating = 5 },
{ title = "Steins;Gate 0", category = "tv", rating = 5 },

-- ================= 4 ESTRELLAS =================
{ title = "1984", category = "book", rating = 4 },
{ title = "Alice in Borderland, Vol. 1", category = "Manga/Manhua", rating = 4 },
{ title = "All You Need Is Kill (Novel)", category = "book", rating = 4 },
{ title = "Biomega, Vol. 1", category = "Manga/Manhua", rating = 4 },
{ title = "Call of the Night, Vol. 1", category = "Manga/Manhua", rating = 4 },
{ title = "Cigarette and Cherry 1", category = "Manga/Manhua", rating = 4 },
{ title = "Dorohedoro, Vol. 1", category = "Manga/Manhua", rating = 4 },
{ title = "Early Years: The Beginning After the End, Book 1", category = "Manga/Manhua", rating = 4 },
{ title = "El Sujeto Nº 1", category = "Manga/Manhua", rating = 4 },
{ title = "El anarquista que se llamaba como yo", category = "book", rating = 4 },
{ title = "El retorno de los brujos", category = "book", rating = 4 },
{ title = "Emergence", category = "book", rating = 4 },
{ title = "Freesia 1", category = "Manga/Manhua", rating = 4 },
{ title = "Go with the clouds, North-by-Northwest, Vol. 1", category = "Manga/Manhua", rating = 4 },
{ title = "Hell's Paradise: Jigokuraku, Vol. 1", category = "Manga/Manhua", rating = 4 },
{ title = "I am a Hero Omnibus Volume 1", category = "Manga/Manhua", rating = 4 },
{ title = "Jagaaan, Tome 1", category = "Manga/Manhua", rating = 4 },
{ title = "James Bond: Origin, Vol. 1", category = "Manga/Manhua", rating = 4 },
{ title = "Knights of Sidonia, Volume 1", category = "Manga/Manhua", rating = 4 },
{ title = "Los Juegos del Hambre 2 - En llamas", category = "book", rating = 4 },
{ title = "Mockingjay", category = "book", rating = 4 },
{ title = "My Dearest Self With Malice Aforethought 1", category = "Manga/Manhua", rating = 4 },
{ title = "My Home Hero, tome 1", category = "Manga/Manhua", rating = 4 },
{ title = "No Longer Human", category = "book", rating = 4 },
{ title = "Noragami: Stray God, Vol. 1", category = "Manga/Manhua", rating = 4 },
{ title = "Old Boy, Vol. 1", category = "Manga/Manhua", rating = 4 },
{ title = "RaW Hero, Vol. 1", category = "Manga/Manhua", rating = 4 },
{ title = "Rebuild World: Volume I Part One: The Alluring Specter", category = "Manga/Manhua", rating = 4 },
{ title = "Solo Leveling, Vol. 1", category = "Manga/Manhua", rating = 4 },
{ title = "Starving Anonymous, Vol. 1", category = "Manga/Manhua", rating = 4 },
{ title = "Technopoly", category = "book", rating = 4 },
{ title = "El juego del ángel", category = "book", rating = 4, badge = "📝", link = "https://alunya.cat/alan/_aforario.html#el-juego-del-%C3%A1ngel-carlos-ruiz-zaf%C3%B3n" },
{ title = "The Breaker New Waves, Vol 1", category = "Manga/Manhua", rating = 4 },
{ title = "The Breaker Volume 1", category = "Manga/Manhua", rating = 4 },
{ title = "The Fable, Vol. 1", category = "Manga/Manhua", rating = 4 },
{ title = "The Horizon", category = "book", rating = 4 },
{ title = "The Infinite Mage", category = "book", rating = 4 },
{ title = "Witch and Mercenary (Light Novel), Vol. 1", category = "Manga/Manhua", rating = 4 },
{ title = "まばゆい恋の", category = "Manga/Manhua", rating = 4 },
{ title = "ダーリン・イン・ザ・フランキス 1", category = "Manga/Manhua", rating = 4 },
{ title = "マイ・ブロークン・マリコ", category = "Manga/Manhua", rating = 4 },
{ title = "仄見える少年 1", category = "Manga/Manhua", rating = 4 },
{ title = "十字架のろくにん 1", category = "Manga/Manhua", rating = 4 },
{ title = "Bastion", category = "game", rating = 4 },
{ title = "Binary Domain", category = "game", rating = 4 },
{ title = "Borderlands 2", category = "game", rating = 4 },
{ title = "Destiny 2", category = "game", rating = 4 },
{ title = "Deus Ex: Human Revolution - Director's Cut", category = "game", rating = 4 },
{ title = "Dishonored", category = "game", rating = 4 },
{ title = "Fallout 4", category = "game", rating = 4 },
{ title = "Pokémon Orange Islands", category = "game", rating = 4 },
{ title = "Pokémon Recharged Yellow", category = "game", rating = 4 },
{ title = "Pokémon Volt White 2", category = "game", rating = 4 },
{ title = "S.T.A.L.K.E.R.: Shadow of Chernobyl", category = "game", rating = 4 },
{ title = "Shadow Warrior", category = "game", rating = 4 },
{ title = "The Witcher 2: Assassins of Kings - Enhanced Edition", category = "game", rating = 4 },
{ title = "Tomb Raider", category = "game", rating = 4 },
{ title = "XCOM: Enemy Unknown", category = "game", rating = 4 },
{ title = "Ace Ventura: Pet Detective", category = "movie", rating = 4 },
{ title = "Ace Ventura: When Nature Calls", category = "movie", rating = 4 },
{ title = "Alien: Covenant", category = "movie", rating = 4 },
{ title = "American History X", category = "movie", rating = 4 },
{ title = "Argo", category = "movie", rating = 4 },
{ title = "As Above, So Below", category = "movie", rating = 4 },
{ title = "Batman Begins", category = "movie", rating = 4 },
{ title = "Big Stan", category = "movie", rating = 4 },
{ title = "Bruce Almighty", category = "movie", rating = 4 },
{ title = "Crazy, Stupid, Love.", category = "movie", rating = 4 },
{ title = "Dennis", category = "movie", rating = 4 },
{ title = "Due Date", category = "movie", rating = 4 },
{ title = "Edge of Tomorrow", category = "movie", rating = 4 },
{ title = "Elysium", category = "movie", rating = 4 },
{ title = "Fighting", category = "movie", rating = 4 },
{ title = "Friends with Benefits", category = "movie", rating = 4 },
{ title = "Full Metal Jacket", category = "movie", rating = 4 },
{ title = "Gladiator", category = "movie", rating = 4 },
{ title = "Grave of the Fireflies", category = "movie", rating = 4 },
{ title = "Hancock", category = "movie", rating = 4 },
{ title = "Hotel Rwanda", category = "movie", rating = 4 },
{ title = "I Am Legend", category = "movie", rating = 4 },
{ title = "Inception", category = "movie", rating = 4 },
{ title = "John Q", category = "movie", rating = 4 },
{ title = "Law Abiding Citizen", category = "movie", rating = 4 },
{ title = "Neighbors", category = "movie", rating = 4 },
{ title = "Never Back Down", category = "movie", rating = 4 },
{ title = "Not Another Teen Movie", category = "movie", rating = 4 },
{ title = "Pale Cocoon", category = "movie", rating = 4 },
{ title = "Patema Inverted", category = "movie", rating = 4 },
{ title = "Phone Booth", category = "movie", rating = 4 },
{ title = "Primer", category = "movie", rating = 4 },
{ title = "RocknRolla", category = "movie", rating = 4 },
{ title = "Se7en", category = "movie", rating = 4 },
{ title = "Snowpiercer", category = "movie", rating = 4 },
{ title = "The Grey", category = "movie", rating = 4 },
{ title = "The Hangover Part II", category = "movie", rating = 4 },
{ title = "The Hangover Part III", category = "movie", rating = 4 },
{ title = "The Intouchables", category = "movie", rating = 4 },
{ title = "The Iron Giant", category = "movie", rating = 4 },
{ title = "The Pursuit of Happyness", category = "movie", rating = 4 },
{ title = "The Road", category = "movie", rating = 4 },
{ title = "Torrente 2: Mission in Marbella", category = "movie", rating = 4 },
{ title = "Torrente 3: The Protector", category = "movie", rating = 4 },
{ title = "Torrente, the Dumb Arm of the Law", category = "movie", rating = 4 },
{ title = "Training Day", category = "movie", rating = 4 },
{ title = "V for Vendetta", category = "movie", rating = 4 },
{ title = "91 Days", category = "tv", rating = 4 },
{ title = "Ajin", category = "tv", rating = 4 },
{ title = "Akame ga Kill!", category = "tv", rating = 4 },
{ title = "Arakawa Under the Bridge", category = "tv", rating = 4 },
{ title = "Asobi Asobase - workshop of fun -", category = "tv", rating = 4 },
{ title = "Assassination Classroom", category = "tv", rating = 4 },
{ title = "Baccano!", category = "tv", rating = 4 },
{ title = "Barakamon", category = "tv", rating = 4 },
{ title = "Black Clover", category = "tv", rating = 4 },
{ title = "Black Mirror", category = "tv", rating = 4 },
{ title = "Blast of Tempest", category = "tv", rating = 4 },
{ title = "Bleach", category = "tv", rating = 4 },
{ title = "Breaking Bad", category = "tv", rating = 4 },
{ title = "Chrome Shelled Regios", category = "tv", rating = 4 },
{ title = "Cowboy Bebop", category = "tv", rating = 4 },
{ title = "Deadman Wonderland", category = "tv", rating = 4 },
{ title = "Deca-Dence", category = "tv", rating = 4 },
{ title = "Devilman Crybaby", category = "tv", rating = 4 },
{ title = "Dorohedoro", category = "tv", rating = 4 },
{ title = "Dragon Ball", category = "tv", rating = 4 },
{ title = "Dragon Ball GT", category = "tv", rating = 4 },
{ title = "Dragon Ball Super", category = "tv", rating = 4 },
{ title = "Dragon Ball Z", category = "tv", rating = 4 },
{ title = "Elfen Lied", category = "tv", rating = 4 },
{ title = "FLCL", category = "tv", rating = 4 },
{ title = "Fire Force", category = "tv", rating = 4 },
{ title = "Fullmetal Alchemist", category = "tv", rating = 4 },
{ title = "Fullmetal Alchemist: Brotherhood", category = "tv", rating = 4 },
{ title = "GANTZ", category = "tv", rating = 4 },
{ title = "Gangsta.", category = "tv", rating = 4 },
{ title = "Gate", category = "tv", rating = 4 },
{ title = "Gleipnir", category = "tv", rating = 4 },
{ title = "Golden Boy", category = "tv", rating = 4 },
{ title = "Great Teacher Onizuka", category = "tv", rating = 4 },
{ title = "Handa-kun", category = "tv", rating = 4 },
{ title = "Hannibal", category = "tv", rating = 4 },
{ title = "Initial D", category = "tv", rating = 4 },
{ title = "InuYasha", category = "tv", rating = 4 },
{ title = "JUJUTSU KAISEN", category = "tv", rating = 4 },
{ title = "Kabaneri of the Iron Fortress", category = "tv", rating = 4 },
{ title = "Kill la Kill", category = "tv", rating = 4 },
{ title = "Kino's Journey", category = "tv", rating = 4 },
{ title = "Lost", category = "tv", rating = 4 },
{ title = "MEGALOBOX", category = "tv", rating = 4 },
{ title = "Misfits", category = "tv", rating = 4 },
{ title = "Mob Psycho 100", category = "tv", rating = 4 },
{ title = "Mr. Robot", category = "tv", rating = 4 },
{ title = "Naruto", category = "tv", rating = 4 },
{ title = "Naruto Shippūden", category = "tv", rating = 4 },
{ title = "One Piece", category = "tv", rating = 4 },
{ title = "One-Punch Man", category = "tv", rating = 4 },
{ title = "Parasyte -the maxim-", category = "tv", rating = 4 },
{ title = "Patema Inverted: Beginning of the Day", category = "tv", rating = 4 },
{ title = "Prison Break", category = "tv", rating = 4 },
{ title = "ReLIFE", category = "tv", rating = 4 },
{ title = "Rin: Daughters of Mnemosyne", category = "tv", rating = 4 },
{ title = "Seraph of the End", category = "tv", rating = 4 },
{ title = "Spartacus", category = "tv", rating = 4 },
{ title = "Super Cub", category = "tv", rating = 4 },
{ title = "Terra Formars", category = "tv", rating = 4 },
{ title = "Terror in Resonance", category = "tv", rating = 4 },
{ title = "Texhnolyze", category = "tv", rating = 4 },
{ title = "The 100", category = "tv", rating = 4 },
{ title = "The Future Diary", category = "tv", rating = 4 },
{ title = "The Numbers", category = "tv", rating = 4 },
{ title = "The Promised Neverland", category = "tv", rating = 4 },
{ title = "The Walking Dead", category = "tv", rating = 4 },
{ title = "To Your Eternity", category = "tv", rating = 4 },
{ title = "Tokyo Ghoul", category = "tv", rating = 4 },
{ title = "Tokyo Magnitude 8.0", category = "tv", rating = 4 },
{ title = "Tokyo Revengers", category = "tv", rating = 4 },
{ title = "Usagi Drop", category = "tv", rating = 4 },
{ title = "Valvrave the Liberator", category = "tv", rating = 4 },
{ title = "Welcome to the N-H-K", category = "tv", rating = 4 },
{ title = "Yu Yu Hakusho", category = "tv", rating = 4 },

-- ================= 3 ESTRELLAS =================
{ title = "Akame Ga Kill!, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Alive: The Final Evolution, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Area D 異能領域, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Ariadne in the Blue Sky, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Arigatō, Vol 1", category = "Manga/Manhua", rating = 3 },
{ title = "Before I Go to Sleep", category = "book", rating = 3 },
{ title = "Beyond Reincarnation: Experience Your Past Lives & Lives Between Lives", category = "book", rating = 3 },
{ title = "Bota Bota", category = "book", rating = 3 },
{ title = "Boy's Abyss, Band 1", category = "Manga/Manhua", rating = 3 },
{ title = "CANDY AND CIGARETTES, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Captain Alatriste (Adventures of Captain Alatriste, #1)", category = "Manga/Manhua", rating = 3 },
{ title = "Cigarette Anthology", category = "book", rating = 3 },
{ title = "Combatants Will Be Dispatched!, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "DEATHTOPIA, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Deadman Wonderland, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "District 14: Season 1", category = "Manga/Manhua", rating = 3 },
{ title = "Divergent", category = "book", rating = 3 },
{ title = "Dragon Head, Volume 1", category = "Manga/Manhua", rating = 3 },
{ title = "Flatland: A Romance of Many Dimensions", category = "book", rating = 3 },
{ title = "Fort of Apocalypse, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Girls' Last Tour, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Gleipnir, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "I Sold My Life for Ten Thousand Yen Per Year, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Imawa no Kuni no Alice RETRY #1", category = "Manga/Manhua", rating = 3 },
{ title = "Im～イム～ 1", category = "Manga/Manhua", rating = 3 },
{ title = "Kaiju No. 8, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Koroshiya Ichi 1", category = "Manga/Manhua", rating = 3 },
{ title = "Leviathan", category = "book", rating = 3 },
{ title = "Libido dominandi", category = "book", rating = 3 },
{ title = "Machimaho: I Messed Up and Made the Wrong Person Into a Magical Girl!, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Manholé T01", category = "book", rating = 3 },
{ title = "Mission: Yozakura Family, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Mister B. Gone", category = "book", rating = 3 },
{ title = "Mx0 tomo 01", category = "Manga/Manhua", rating = 3 },
{ title = "My Dress-Up Darling, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "No Longer Human, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Othello", category = "book", rating = 3 },
{ title = "Parasyte, Volume 1", category = "Manga/Manhua", rating = 3 },
{ title = "Prison Lab 1", category = "Manga/Manhua", rating = 3 },
{ title = "ROLL Over and DIE: I Will Fight for an Ordinary Life with My Love and Cursed Sword! (Light Novel), Vol. 5", category = "Manga/Manhua", rating = 3 },
{ title = "Remina", category = "Manga/Manhua", rating = 3 },
{ title = "Roppongi", category = "Manga/Manhua", rating = 3 },
{ title = "Saiyūki, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Soloist in a Cage, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Stravaganza Volume 1", category = "Manga/Manhua", rating = 3 },
{ title = "Sugar Dark: Umerareta Yami to Shoujo", category = "book", rating = 3 },
{ title = "Sweet Home, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "The Butler Did It and Other Plays Level 1 Oxford Bookworms Library", category = "book", rating = 3 },
{ title = "The Great Gatsby", category = "book", rating = 3 },
{ title = "The Metamorphosis", category = "book", rating = 3 },
{ title = "UQ HOLDER!, Vol. 1", category = "Manga/Manhua", rating = 3 },
{ title = "Undead and Unemployed", category = "book", rating = 3 },
{ title = "Viaje al centro de la tierra", category = "book", rating = 3 },
{ title = "Weavers #1", category = "Manga/Manhua", rating = 3 },
{ title = "pygmalion", category = "Manga/Manhua", rating = 3 },
{ title = "unOrdinary", category = "Manga/Manhua", rating = 3 },
{ title = "ケンガンアシュラ 1", category = "Manga/Manhua", rating = 3 },
{ title = "ダウト 1", category = "Manga/Manhua", rating = 3 },
{ title = "ハピネス 1", category = "Manga/Manhua", rating = 3 },
{ title = "ヒミズ 1", category = "Manga/Manhua", rating = 3 },
{ title = "マッシュル-MASHLE- 1", category = "Manga/Manhua", rating = 3 },
{ title = "両面宿儺", category = "Manga/Manhua", rating = 3 },
{ title = "Ｂｏｉｃｈｉ作品集 ＨＯＴＥＬ", category = "Manga/Manhua", rating = 3 },
{ title = "Black Mesa", category = "game", rating = 3 },
{ title = "Counter-Strike: Global Offensive", category = "game", rating = 3 },
{ title = "DmC: Devil May Cry", category = "game", rating = 3 },
{ title = "Half-Life 2", category = "game", rating = 3 },
{ title = "Hitman: Absolution", category = "game", rating = 3 },
{ title = "New Super Mario Bros.", category = "game", rating = 3 },
{ title = "Pokémon Crystal Version", category = "game", rating = 3 },
{ title = "Pokémon Dreams", category = "game", rating = 3 },
{ title = "Rogue Legacy", category = "game", rating = 3 },
{ title = "S.T.A.L.K.E.R.: Call of Pripyat", category = "game", rating = 3 },
{ title = "S.T.A.L.K.E.R.: Clear Sky", category = "game", rating = 3 },
{ title = "SteamWorld Dig", category = "game", rating = 3 },
{ title = "The Bureau: XCOM Declassified", category = "game", rating = 3 },
{ title = "Wolfenstein: The New Order", category = "game", rating = 3 },
{ title = "1917", category = "movie", rating = 3 },
{ title = "21 Jump Street", category = "movie", rating = 3 },
{ title = "Alien", category = "movie", rating = 3 },
{ title = "All Quiet on the Western Front", category = "movie", rating = 3 },
{ title = "Annihilation", category = "movie", rating = 3 },
{ title = "Blade Runner 2049", category = "movie", rating = 3 },
{ title = "Don't Look Up", category = "movie", rating = 3 },
{ title = "Hugo", category = "movie", rating = 3 },
{ title = "Invictus", category = "movie", rating = 3 },
{ title = "Limitless", category = "movie", rating = 3 },
{ title = "Men in Black", category = "movie", rating = 3 },
{ title = "Men in Black 3", category = "movie", rating = 3 },
{ title = "Men in Black II", category = "movie", rating = 3 },
{ title = "Once Upon a Time... in Hollywood", category = "movie", rating = 3 },
{ title = "Ong-Bak", category = "movie", rating = 3 },
{ title = "Prometheus", category = "movie", rating = 3 },
{ title = "Requiem for a Dream", category = "movie", rating = 3 },
{ title = "Ted", category = "movie", rating = 3 },
{ title = "The Book of Eli", category = "movie", rating = 3 },
{ title = "The Last Castle", category = "movie", rating = 3 },
{ title = "The Machinist", category = "movie", rating = 3 },
{ title = "The Mule", category = "movie", rating = 3 },
{ title = "The Platform", category = "movie", rating = 3 },
{ title = "The Silence of Others", category = "movie", rating = 3 },
{ title = "Torrente 4: Lethal crisis", category = "movie", rating = 3 },
{ title = "Torrente 5", category = "movie", rating = 3 },
{ title = "A Place Further than the Universe", category = "tv", rating = 3 },
{ title = "Aldnoah.Zero", category = "tv", rating = 3 },
{ title = "Another", category = "tv", rating = 3 },
{ title = "BAKI", category = "tv", rating = 3 },
{ title = "Berserk", category = "tv", rating = 3 },
{ title = "Cautious Hero: The Hero Is Overpowered but Overly Cautious", category = "tv", rating = 3 },
{ title = "Clannad", category = "tv", rating = 3 },
{ title = "Code:Breaker", category = "tv", rating = 3 },
{ title = "Death Note", category = "tv", rating = 3 },
{ title = "Eden of the East", category = "tv", rating = 3 },
{ title = "Ergo Proxy", category = "tv", rating = 3 },
{ title = "Falling Skies", category = "tv", rating = 3 },
{ title = "Fate/stay night [Unlimited Blade Works]", category = "tv", rating = 3 },
{ title = "Fear the Walking Dead", category = "tv", rating = 3 },
{ title = "Game of Thrones", category = "tv", rating = 3 },
{ title = "Girls' Last Tour", category = "tv", rating = 3 },
{ title = "Haven't You Heard? I'm Sakamoto", category = "tv", rating = 3 },
{ title = "Hellsing", category = "tv", rating = 3 },
{ title = "Hellsing Ultimate", category = "tv", rating = 3 },
{ title = "Higehiro: After Being Rejected, I Shaved and Took in a High School Runaway", category = "tv", rating = 3 },
{ title = "High School D×D", category = "tv", rating = 3 },
{ title = "High School of the Dead", category = "tv", rating = 3 },
{ title = "How Heavy Are the Dumbbells You Lift?", category = "tv", rating = 3 },
{ title = "INUYASHIKI LAST HERO", category = "tv", rating = 3 },
{ title = "Jericho", category = "tv", rating = 3 },
{ title = "Jormungand", category = "tv", rating = 3 },
{ title = "Jyu-Oh-Sei", category = "tv", rating = 3 },
{ title = "KUROKAMI The Animation", category = "tv", rating = 3 },
{ title = "Killing Eve", category = "tv", rating = 3 },
{ title = "Knights of Sidonia", category = "tv", rating = 3 },
{ title = "Kure-nai", category = "tv", rating = 3 },
{ title = "Kurozuka", category = "tv", rating = 3 },
{ title = "Lost in Space", category = "tv", rating = 3 },
{ title = "No Guns Life", category = "tv", rating = 3 },
{ title = "No. 6", category = "tv", rating = 3 },
{ title = "Noragami", category = "tv", rating = 3 },
{ title = "Planetes", category = "tv", rating = 3 },
{ title = "Ray Donovan", category = "tv", rating = 3 },
{ title = "Re:ZERO -Starting Life in Another World-", category = "tv", rating = 3 },
{ title = "Real Humans", category = "tv", rating = 3 },
{ title = "Rome", category = "tv", rating = 3 },
{ title = "Rurouni Kenshin", category = "tv", rating = 3 },
{ title = "SING \"YESTERDAY\" FOR ME", category = "tv", rating = 3 },
{ title = "Shadows House", category = "tv", rating = 3 },
{ title = "Sword Art Online", category = "tv", rating = 3 },
{ title = "TRIGUN", category = "tv", rating = 3 },
{ title = "The Comic Artist and His Assistants", category = "tv", rating = 3 },
{ title = "The Devil Is a Part-Timer!", category = "tv", rating = 3 },
{ title = "The Fruit of Grisaia", category = "tv", rating = 3 },
{ title = "The Irregular at Magic High School", category = "tv", rating = 3 },
{ title = "The King's Avatar", category = "tv", rating = 3 },
{ title = "The Seven Deadly Sins", category = "tv", rating = 3 },
{ title = "Time of Eve", category = "tv", rating = 3 },
{ title = "Vivy: Fluorite Eye's Song", category = "tv", rating = 3 },
{ title = "Young Black Jack", category = "tv", rating = 3 },
{ title = "Zetman", category = "tv", rating = 3 },

-- ================= 2 ESTRELLAS =================
{ title = "Adam Sharp #6: Code Word Kangaroo", category = "Manga/Manhua", rating = 2 },
{ title = "Believers", category = "Manga/Manhua", rating = 2 },
{ title = "City of Bones", category = "book", rating = 2 },
{ title = "El Medico", category = "book", rating = 2 },
{ title = "King of Thorn, Vol. 1", category = "Manga/Manhua", rating = 2 },
{ title = "Metro Survive, Vol. 1", category = "Manga/Manhua", rating = 2 },
{ title = "The Otherworlder, Exploring the Dungeon, Vol. 1", category = "Manga/Manhua", rating = 2 },
{ title = "アヤシモン 1", category = "Manga/Manhua", rating = 2 },
{ title = "ドクムシ 1", category = "Manga/Manhua", rating = 2 },
{ title = "Advance Wars: Dual Strike", category = "game", rating = 2 },
{ title = "Black Desert", category = "game", rating = 2 },
{ title = "Burnout Paradise: The Ultimate Box", category = "game", rating = 2 },
{ title = "Castlevania: Order of Ecclesia", category = "game", rating = 2 },
{ title = "Counter-Strike 2", category = "game", rating = 2 },
{ title = "FTL: Faster Than Light", category = "game", rating = 2 },
{ title = "Gods Will Be Watching", category = "game", rating = 2 },
{ title = "Hotel Dusk: Room 215", category = "game", rating = 2 },
{ title = "Hotline Miami", category = "game", rating = 2 },
{ title = "How to Survive", category = "game", rating = 2 },
{ title = "IdleOn", category = "game", rating = 2 },
{ title = "Kirby Super Star Ultra", category = "game", rating = 2 },
{ title = "Lunar Knights", category = "game", rating = 2 },
{ title = "Mario & Luigi: Bowser's Inside Story", category = "game", rating = 2 },
{ title = "Megaman ZX Genesis", category = "game", rating = 2 },
{ title = "Metal Slug 7", category = "game", rating = 2 },
{ title = "Payday 2", category = "game", rating = 2 },
{ title = "Pokémon Mystery Dungeon: Blue Rescue Team", category = "game", rating = 2 },
{ title = "Pokémon Renegade Platinum", category = "game", rating = 2 },
{ title = "Portal", category = "game", rating = 2 },
{ title = "Rage", category = "game", rating = 2 },
{ title = "Rising Storm/Red Orchestra 2 Multiplayer", category = "game", rating = 2 },
{ title = "Solatorobo: Red the Hunter", category = "game", rating = 2 },
{ title = "Summoners War: Sky Arena", category = "game", rating = 2 },
{ title = "Team Fortress 2", category = "game", rating = 2 },
{ title = "Terranigma", category = "game", rating = 2 },
{ title = "Joker", category = "movie", rating = 2 },
{ title = "Monsters", category = "movie", rating = 2 },
{ title = "Nerve", category = "movie", rating = 2 },
{ title = "Overlord", category = "movie", rating = 2 },
{ title = "Dragon Quest: The Adventure of Dai", category = "season", rating = 2 },
{ title = "24: Legacy", category = "tv", rating = 2 },
{ title = "7SEEDS", category = "tv", rating = 2 },
{ title = "A Certain Magical Index", category = "tv", rating = 2 },
{ title = "A Certain Scientific Accelerator", category = "tv", rating = 2 },
{ title = "A.I.C.O. -Incarnation-", category = "tv", rating = 2 },
{ title = "Alice in Borderland", category = "tv", rating = 2 },
{ title = "Arrow", category = "tv", rating = 2 },
{ title = "BACK ARROW", category = "tv", rating = 2 },
{ title = "Black Bullet", category = "tv", rating = 2 },
{ title = "Black Lagoon", category = "tv", rating = 2 },
{ title = "Blood Blockade Battlefront", category = "tv", rating = 2 },
{ title = "Blood Lad", category = "tv", rating = 2 },
{ title = "Blue Exorcist", category = "tv", rating = 2 },
{ title = "Btooom!", category = "tv", rating = 2 },
{ title = "CESTVS -The Roman Fighter-", category = "tv", rating = 2 },
{ title = "Carnivàle", category = "tv", rating = 2 },
{ title = "Casshern Sins", category = "tv", rating = 2 },
{ title = "Charlotte", category = "tv", rating = 2 },
{ title = "Chivalry of a Failed Knight", category = "tv", rating = 2 },
{ title = "Colony", category = "tv", rating = 2 },
{ title = "Corpse Party: Tortured Souls", category = "tv", rating = 2 },
{ title = "Death Parade", category = "tv", rating = 2 },
{ title = "Demon King Daimao", category = "tv", rating = 2 },
{ title = "Dominion", category = "tv", rating = 2 },
{ title = "Dororo", category = "tv", rating = 2 },
{ title = "Dr. STONE", category = "tv", rating = 2 },
{ title = "Dragon Quest: The Adventure of Dai", category = "tv", rating = 2 },
{ title = "Electromagnetic Girlfriend", category = "tv", rating = 2 },
{ title = "From the New World", category = "tv", rating = 2 },
{ title = "Goblin Slayer", category = "tv", rating = 2 },
{ title = "God Eater", category = "tv", rating = 2 },
{ title = "Gurren Lagann", category = "tv", rating = 2 },
{ title = "Heaven's Lost Property", category = "tv", rating = 2 },
{ title = "Higurashi: When They Cry - NEW", category = "tv", rating = 2 },
{ title = "I'm Standing on a Million Lives", category = "tv", rating = 2 },
{ title = "Into the Badlands", category = "tv", rating = 2 },
{ title = "Karas", category = "tv", rating = 2 },
{ title = "Legion", category = "tv", rating = 2 },
{ title = "MARS RED", category = "tv", rating = 2 },
{ title = "Magatsu Wahrheit: Zuerst", category = "tv", rating = 2 },
{ title = "My Hero Academia", category = "tv", rating = 2 },
{ title = "Ousama Game The Animation", category = "tv", rating = 2 },
{ title = "Phantom: Requiem for the Phantom", category = "tv", rating = 2 },
{ title = "Plunderer", category = "tv", rating = 2 },
{ title = "Prison School", category = "tv", rating = 2 },
{ title = "Rage of Bahamut", category = "tv", rating = 2 },
{ title = "Re:Creators", category = "tv", rating = 2 },
{ title = "Redo of Healer", category = "tv", rating = 2 },
{ title = "SWORD GAI: The Animation", category = "tv", rating = 2 },
{ title = "Shooter", category = "tv", rating = 2 },
{ title = "Sorcerous Stabber Orphen", category = "tv", rating = 2 },
{ title = "The Expanse", category = "tv", rating = 2 },
{ title = "The Last Ship", category = "tv", rating = 2 },
{ title = "The Leftovers", category = "tv", rating = 2 },
{ title = "The Legend of the Legendary Heroes", category = "tv", rating = 2 },
{ title = "The Man in the High Castle", category = "tv", rating = 2 },
{ title = "The Misfit of Demon King Academy", category = "tv", rating = 2 },
{ title = "The Strain", category = "tv", rating = 2 },
{ title = "The Zone", category = "tv", rating = 2 },
{ title = "Trinity Seven", category = "tv", rating = 2 },
{ title = "Under the Dome", category = "tv", rating = 2 },
{ title = "Unlimited Psychic Squad", category = "tv", rating = 2 },
{ title = "Utopia", category = "tv", rating = 2 },
{ title = "When They See Us", category = "tv", rating = 2 },
{ title = "[C] The Money of Soul and Possibility Control", category = "tv", rating = 2 },
}